# Generated by Django 4.0.4 on 2022-05-20 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='dimensions',
            field=models.CharField(default='N/A', max_length=255),
        ),
    ]
